// AUTO-GENERATED by scripts/gen-types.mjs — do not edit by hand.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      attribute_options: {
        Row: {
          id: string
          kind: Database['public']['Enums']['attribute_kind']
          value: string
          hex: string | null
          sort_order: number
        }
        Insert: {
          id?: string
          kind: Database['public']['Enums']['attribute_kind']
          value: string
          hex?: string | null
          sort_order?: number
        }
        Update: {
          id?: string
          kind?: Database['public']['Enums']['attribute_kind']
          value?: string
          hex?: string | null
          sort_order?: number
        }
        Relationships: []
      }
      audit_log: {
        Row: {
          id: number
          actor_id: string | null
          action: string
          target_table: string
          target_id: string | null
          previous_value: Json | null
          new_value: Json | null
          created_at: string
        }
        Insert: {
          id?: number
          actor_id?: string | null
          action: string
          target_table: string
          target_id?: string | null
          previous_value?: Json | null
          new_value?: Json | null
          created_at?: string
        }
        Update: {
          id?: number
          actor_id?: string | null
          action?: string
          target_table?: string
          target_id?: string | null
          previous_value?: Json | null
          new_value?: Json | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'audit_log_actor_id_fkey'
            columns: ['actor_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      cart_items: {
        Row: {
          user_id: string
          variant_id: string
          quantity: number
          added_at: string
        }
        Insert: {
          user_id: string
          variant_id: string
          quantity: number
          added_at?: string
        }
        Update: {
          user_id?: string
          variant_id?: string
          quantity?: number
          added_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'cart_items_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'cart_items_variant_id_fkey'
            columns: ['variant_id']
            isOneToOne: false
            referencedRelation: 'product_variants'
            referencedColumns: ['id']
          }
        ]
      }
      cash_sessions: {
        Row: {
          id: string
          staff_id: string
          status: string
          opening_float: number
          opened_at: string
          closed_at: string | null
          expected_cash: number | null
          counted_cash: number | null
          discrepancy: number | null
          notes: string | null
        }
        Insert: {
          id?: string
          staff_id: string
          status?: string
          opening_float?: number
          opened_at?: string
          closed_at?: string | null
          expected_cash?: number | null
          counted_cash?: number | null
          discrepancy?: number | null
          notes?: string | null
        }
        Update: {
          id?: string
          staff_id?: string
          status?: string
          opening_float?: number
          opened_at?: string
          closed_at?: string | null
          expected_cash?: number | null
          counted_cash?: number | null
          discrepancy?: number | null
          notes?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'cash_sessions_staff_id_fkey'
            columns: ['staff_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      categories: {
        Row: {
          id: string
          name: string
          slug: string
          parent_id: string | null
          description: string | null
          image_url: string | null
          sort_order: number
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          parent_id?: string | null
          description?: string | null
          image_url?: string | null
          sort_order?: number
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          parent_id?: string | null
          description?: string | null
          image_url?: string | null
          sort_order?: number
          is_active?: boolean
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'categories_parent_id_fkey'
            columns: ['parent_id']
            isOneToOne: false
            referencedRelation: 'categories'
            referencedColumns: ['id']
          }
        ]
      }
      coupons: {
        Row: {
          id: string
          code: string
          description: string | null
          type: Database['public']['Enums']['coupon_type']
          value: number
          min_subtotal: number
          starts_at: string | null
          ends_at: string | null
          max_uses: number | null
          used_count: number
          is_active: boolean
          created_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          code: string
          description?: string | null
          type?: Database['public']['Enums']['coupon_type']
          value: number
          min_subtotal?: number
          starts_at?: string | null
          ends_at?: string | null
          max_uses?: number | null
          used_count?: number
          is_active?: boolean
          created_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          code?: string
          description?: string | null
          type?: Database['public']['Enums']['coupon_type']
          value?: number
          min_subtotal?: number
          starts_at?: string | null
          ends_at?: string | null
          max_uses?: number | null
          used_count?: number
          is_active?: boolean
          created_by?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'coupons_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      customer_addresses: {
        Row: {
          id: string
          user_id: string
          label: string | null
          recipient_name: string
          phone: string
          zone_id: string | null
          address_line: string
          landmark: string | null
          is_default: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          label?: string | null
          recipient_name: string
          phone: string
          zone_id?: string | null
          address_line: string
          landmark?: string | null
          is_default?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          label?: string | null
          recipient_name?: string
          phone?: string
          zone_id?: string | null
          address_line?: string
          landmark?: string | null
          is_default?: boolean
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'customer_addresses_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'customer_addresses_zone_id_fkey'
            columns: ['zone_id']
            isOneToOne: false
            referencedRelation: 'delivery_zones'
            referencedColumns: ['id']
          }
        ]
      }
      delivery_zones: {
        Row: {
          id: string
          name: string
          description: string | null
          fee: number
          eta: string | null
          cod_allowed: boolean
          is_active: boolean
          sort_order: number
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          fee?: number
          eta?: string | null
          cod_allowed?: boolean
          is_active?: boolean
          sort_order?: number
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          fee?: number
          eta?: string | null
          cod_allowed?: boolean
          is_active?: boolean
          sort_order?: number
          created_at?: string
        }
        Relationships: []
      }
      newsletter_subscribers: {
        Row: {
          email: string
          created_at: string
        }
        Insert: {
          email: string
          created_at?: string
        }
        Update: {
          email?: string
          created_at?: string
        }
        Relationships: []
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          target_role: Database['public']['Enums']['app_role'] | null
          type: Database['public']['Enums']['notification_type']
          title: string
          message: string
          link: string | null
          read_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          target_role?: Database['public']['Enums']['app_role'] | null
          type: Database['public']['Enums']['notification_type']
          title: string
          message: string
          link?: string | null
          read_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          target_role?: Database['public']['Enums']['app_role'] | null
          type?: Database['public']['Enums']['notification_type']
          title?: string
          message?: string
          link?: string | null
          read_at?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'notifications_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      order_item_costs: {
        Row: {
          order_item_id: string
          unit_cost: number
        }
        Insert: {
          order_item_id: string
          unit_cost?: number
        }
        Update: {
          order_item_id?: string
          unit_cost?: number
        }
        Relationships: [
          {
            foreignKeyName: 'order_item_costs_order_item_id_fkey'
            columns: ['order_item_id']
            isOneToOne: true
            referencedRelation: 'order_items'
            referencedColumns: ['id']
          }
        ]
      }
      order_items: {
        Row: {
          id: string
          order_id: string
          variant_id: string | null
          product_id: string | null
          product_name: string
          variant_label: string | null
          sku: string | null
          image_url: string | null
          quantity: number
          unit_price: number
          line_total: number
        }
        Insert: {
          id?: string
          order_id: string
          variant_id?: string | null
          product_id?: string | null
          product_name: string
          variant_label?: string | null
          sku?: string | null
          image_url?: string | null
          quantity: number
          unit_price: number
          line_total: number
        }
        Update: {
          id?: string
          order_id?: string
          variant_id?: string | null
          product_id?: string | null
          product_name?: string
          variant_label?: string | null
          sku?: string | null
          image_url?: string | null
          quantity?: number
          unit_price?: number
          line_total?: number
        }
        Relationships: [
          {
            foreignKeyName: 'order_items_order_id_fkey'
            columns: ['order_id']
            isOneToOne: false
            referencedRelation: 'orders'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'order_items_product_id_fkey'
            columns: ['product_id']
            isOneToOne: false
            referencedRelation: 'products'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'order_items_variant_id_fkey'
            columns: ['variant_id']
            isOneToOne: false
            referencedRelation: 'product_variants'
            referencedColumns: ['id']
          }
        ]
      }
      order_status_history: {
        Row: {
          id: number
          order_id: string
          status: Database['public']['Enums']['order_status']
          note: string | null
          changed_by: string | null
          created_at: string
        }
        Insert: {
          id?: number
          order_id: string
          status: Database['public']['Enums']['order_status']
          note?: string | null
          changed_by?: string | null
          created_at?: string
        }
        Update: {
          id?: number
          order_id?: string
          status?: Database['public']['Enums']['order_status']
          note?: string | null
          changed_by?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'order_status_history_changed_by_fkey'
            columns: ['changed_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'order_status_history_order_id_fkey'
            columns: ['order_id']
            isOneToOne: false
            referencedRelation: 'orders'
            referencedColumns: ['id']
          }
        ]
      }
      orders: {
        Row: {
          id: string
          order_number: string
          channel: Database['public']['Enums']['order_channel']
          customer_id: string | null
          contact_name: string | null
          contact_phone: string | null
          contact_email: string | null
          status: Database['public']['Enums']['order_status']
          delivery_method: Database['public']['Enums']['delivery_method']
          delivery_zone_id: string | null
          delivery_zone_name: string | null
          delivery_address: string | null
          delivery_notes: string | null
          delivery_fee: number
          payment_method: Database['public']['Enums']['payment_method']
          payment_status: Database['public']['Enums']['payment_status']
          subtotal: number
          discount_total: number
          total: number
          coupon_code: string | null
          discount_reason: string | null
          discount_by: string | null
          handled_by: string | null
          cash_session_id: string | null
          amount_tendered: number | null
          change_given: number | null
          tracking_token: string
          void_reason: string | null
          voided_by: string | null
          voided_at: string | null
          refund_reason: string | null
          refunded_by: string | null
          refunded_at: string | null
          placed_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          order_number?: string
          channel?: Database['public']['Enums']['order_channel']
          customer_id?: string | null
          contact_name?: string | null
          contact_phone?: string | null
          contact_email?: string | null
          status?: Database['public']['Enums']['order_status']
          delivery_method: Database['public']['Enums']['delivery_method']
          delivery_zone_id?: string | null
          delivery_zone_name?: string | null
          delivery_address?: string | null
          delivery_notes?: string | null
          delivery_fee?: number
          payment_method: Database['public']['Enums']['payment_method']
          payment_status?: Database['public']['Enums']['payment_status']
          subtotal: number
          discount_total?: number
          total: number
          coupon_code?: string | null
          discount_reason?: string | null
          discount_by?: string | null
          handled_by?: string | null
          cash_session_id?: string | null
          amount_tendered?: number | null
          change_given?: number | null
          tracking_token?: string
          void_reason?: string | null
          voided_by?: string | null
          voided_at?: string | null
          refund_reason?: string | null
          refunded_by?: string | null
          refunded_at?: string | null
          placed_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          order_number?: string
          channel?: Database['public']['Enums']['order_channel']
          customer_id?: string | null
          contact_name?: string | null
          contact_phone?: string | null
          contact_email?: string | null
          status?: Database['public']['Enums']['order_status']
          delivery_method?: Database['public']['Enums']['delivery_method']
          delivery_zone_id?: string | null
          delivery_zone_name?: string | null
          delivery_address?: string | null
          delivery_notes?: string | null
          delivery_fee?: number
          payment_method?: Database['public']['Enums']['payment_method']
          payment_status?: Database['public']['Enums']['payment_status']
          subtotal?: number
          discount_total?: number
          total?: number
          coupon_code?: string | null
          discount_reason?: string | null
          discount_by?: string | null
          handled_by?: string | null
          cash_session_id?: string | null
          amount_tendered?: number | null
          change_given?: number | null
          tracking_token?: string
          void_reason?: string | null
          voided_by?: string | null
          voided_at?: string | null
          refund_reason?: string | null
          refunded_by?: string | null
          refunded_at?: string | null
          placed_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'orders_cash_session_id_fkey'
            columns: ['cash_session_id']
            isOneToOne: false
            referencedRelation: 'cash_sessions'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'orders_customer_id_fkey'
            columns: ['customer_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'orders_delivery_zone_id_fkey'
            columns: ['delivery_zone_id']
            isOneToOne: false
            referencedRelation: 'delivery_zones'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'orders_discount_by_fkey'
            columns: ['discount_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'orders_handled_by_fkey'
            columns: ['handled_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'orders_refunded_by_fkey'
            columns: ['refunded_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'orders_voided_by_fkey'
            columns: ['voided_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      payments: {
        Row: {
          id: string
          order_id: string
          amount: number
          method: Database['public']['Enums']['payment_method']
          status: Database['public']['Enums']['payment_status']
          mpesa_checkout_request_id: string | null
          mpesa_receipt: string | null
          card_ref: string | null
          reference: string | null
          payer_phone: string | null
          received_by: string | null
          raw: Json | null
          created_at: string
          paid_at: string | null
        }
        Insert: {
          id?: string
          order_id: string
          amount: number
          method: Database['public']['Enums']['payment_method']
          status?: Database['public']['Enums']['payment_status']
          mpesa_checkout_request_id?: string | null
          mpesa_receipt?: string | null
          card_ref?: string | null
          reference?: string | null
          payer_phone?: string | null
          received_by?: string | null
          raw?: Json | null
          created_at?: string
          paid_at?: string | null
        }
        Update: {
          id?: string
          order_id?: string
          amount?: number
          method?: Database['public']['Enums']['payment_method']
          status?: Database['public']['Enums']['payment_status']
          mpesa_checkout_request_id?: string | null
          mpesa_receipt?: string | null
          card_ref?: string | null
          reference?: string | null
          payer_phone?: string | null
          received_by?: string | null
          raw?: Json | null
          created_at?: string
          paid_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'payments_order_id_fkey'
            columns: ['order_id']
            isOneToOne: false
            referencedRelation: 'orders'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'payments_received_by_fkey'
            columns: ['received_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      product_variants: {
        Row: {
          id: string
          product_id: string
          size: string | null
          colour: string | null
          sku: string
          barcode_value: string
          selling_price: number
          quantity_on_hand: number
          low_stock_threshold: number
          image_url: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          product_id: string
          size?: string | null
          colour?: string | null
          sku: string
          barcode_value: string
          selling_price: number
          quantity_on_hand?: number
          low_stock_threshold?: number
          image_url?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          product_id?: string
          size?: string | null
          colour?: string | null
          sku?: string
          barcode_value?: string
          selling_price?: number
          quantity_on_hand?: number
          low_stock_threshold?: number
          image_url?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'product_variants_product_id_fkey'
            columns: ['product_id']
            isOneToOne: false
            referencedRelation: 'products'
            referencedColumns: ['id']
          }
        ]
      }
      products: {
        Row: {
          id: string
          category_id: string
          name: string
          slug: string
          description: string | null
          base_price: number
          compare_at_price: number | null
          images: string[]
          tags: string[]
          is_active: boolean
          is_featured: boolean
          price_min: number | null
          price_max: number | null
          total_stock: number
          sizes: string[]
          colours: string[]
          rating_avg: number
          rating_count: number
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          category_id: string
          name: string
          slug: string
          description?: string | null
          base_price?: number
          compare_at_price?: number | null
          images?: string[]
          tags?: string[]
          is_active?: boolean
          is_featured?: boolean
          price_min?: number | null
          price_max?: number | null
          total_stock?: number
          sizes?: string[]
          colours?: string[]
          rating_avg?: number
          rating_count?: number
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          category_id?: string
          name?: string
          slug?: string
          description?: string | null
          base_price?: number
          compare_at_price?: number | null
          images?: string[]
          tags?: string[]
          is_active?: boolean
          is_featured?: boolean
          price_min?: number | null
          price_max?: number | null
          total_stock?: number
          sizes?: string[]
          colours?: string[]
          rating_avg?: number
          rating_count?: number
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'products_category_id_fkey'
            columns: ['category_id']
            isOneToOne: false
            referencedRelation: 'categories'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'products_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      profiles: {
        Row: {
          id: string
          role: Database['public']['Enums']['app_role']
          full_name: string | null
          email: string | null
          phone: string | null
          preferred_payment: Database['public']['Enums']['payment_method'] | null
          marketing_opt_in: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          role?: Database['public']['Enums']['app_role']
          full_name?: string | null
          email?: string | null
          phone?: string | null
          preferred_payment?: Database['public']['Enums']['payment_method'] | null
          marketing_opt_in?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          role?: Database['public']['Enums']['app_role']
          full_name?: string | null
          email?: string | null
          phone?: string | null
          preferred_payment?: Database['public']['Enums']['payment_method'] | null
          marketing_opt_in?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      push_subscriptions: {
        Row: {
          id: string
          user_id: string
          endpoint: string
          p256dh: string
          auth: string
          user_agent: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          endpoint: string
          p256dh: string
          auth: string
          user_agent?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          endpoint?: string
          p256dh?: string
          auth?: string
          user_agent?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'push_subscriptions_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      rate_limits: {
        Row: {
          key: string
          window_start: string
          hits: number
        }
        Insert: {
          key: string
          window_start: string
          hits: number
        }
        Update: {
          key?: string
          window_start?: string
          hits?: number
        }
        Relationships: []
      }
      reviews: {
        Row: {
          id: string
          product_id: string
          user_id: string
          author_name: string | null
          rating: number
          title: string | null
          comment: string | null
          status: Database['public']['Enums']['review_status']
          verified_purchase: boolean
          created_at: string
        }
        Insert: {
          id?: string
          product_id: string
          user_id: string
          author_name?: string | null
          rating: number
          title?: string | null
          comment?: string | null
          status?: Database['public']['Enums']['review_status']
          verified_purchase?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          product_id?: string
          user_id?: string
          author_name?: string | null
          rating?: number
          title?: string | null
          comment?: string | null
          status?: Database['public']['Enums']['review_status']
          verified_purchase?: boolean
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'reviews_product_id_fkey'
            columns: ['product_id']
            isOneToOne: false
            referencedRelation: 'products'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'reviews_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      staff: {
        Row: {
          user_id: string
          assigned_category_ids: string[]
          can_view_margins: boolean
          discount_limit_pct: number
          is_active: boolean
          notes: string | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          user_id: string
          assigned_category_ids?: string[]
          can_view_margins?: boolean
          discount_limit_pct?: number
          is_active?: boolean
          notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          user_id?: string
          assigned_category_ids?: string[]
          can_view_margins?: boolean
          discount_limit_pct?: number
          is_active?: boolean
          notes?: string | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'staff_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'staff_user_id_fkey'
            columns: ['user_id']
            isOneToOne: true
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      stock_adjustments: {
        Row: {
          id: string
          variant_id: string
          quantity_delta: number
          quantity_after: number | null
          reason: Database['public']['Enums']['stock_reason']
          note: string | null
          new_cost_price: number | null
          order_id: string | null
          stock_count_id: string | null
          adjusted_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          variant_id: string
          quantity_delta: number
          quantity_after?: number | null
          reason: Database['public']['Enums']['stock_reason']
          note?: string | null
          new_cost_price?: number | null
          order_id?: string | null
          stock_count_id?: string | null
          adjusted_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          variant_id?: string
          quantity_delta?: number
          quantity_after?: number | null
          reason?: Database['public']['Enums']['stock_reason']
          note?: string | null
          new_cost_price?: number | null
          order_id?: string | null
          stock_count_id?: string | null
          adjusted_by?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'stock_adjustments_adjusted_by_fkey'
            columns: ['adjusted_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'stock_adjustments_order_id_fkey'
            columns: ['order_id']
            isOneToOne: false
            referencedRelation: 'orders'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'stock_adjustments_stock_count_id_fkey'
            columns: ['stock_count_id']
            isOneToOne: false
            referencedRelation: 'stock_counts'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'stock_adjustments_variant_id_fkey'
            columns: ['variant_id']
            isOneToOne: false
            referencedRelation: 'product_variants'
            referencedColumns: ['id']
          }
        ]
      }
      stock_count_lines: {
        Row: {
          count_id: string
          variant_id: string
          expected: number
          counted: number | null
          counted_by: string | null
          updated_at: string
        }
        Insert: {
          count_id: string
          variant_id: string
          expected: number
          counted?: number | null
          counted_by?: string | null
          updated_at?: string
        }
        Update: {
          count_id?: string
          variant_id?: string
          expected?: number
          counted?: number | null
          counted_by?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'stock_count_lines_count_id_fkey'
            columns: ['count_id']
            isOneToOne: false
            referencedRelation: 'stock_counts'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'stock_count_lines_counted_by_fkey'
            columns: ['counted_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'stock_count_lines_variant_id_fkey'
            columns: ['variant_id']
            isOneToOne: false
            referencedRelation: 'product_variants'
            referencedColumns: ['id']
          }
        ]
      }
      stock_counts: {
        Row: {
          id: string
          title: string
          category_id: string | null
          status: string
          notes: string | null
          started_by: string | null
          created_at: string
          completed_by: string | null
          completed_at: string | null
        }
        Insert: {
          id?: string
          title: string
          category_id?: string | null
          status?: string
          notes?: string | null
          started_by?: string | null
          created_at?: string
          completed_by?: string | null
          completed_at?: string | null
        }
        Update: {
          id?: string
          title?: string
          category_id?: string | null
          status?: string
          notes?: string | null
          started_by?: string | null
          created_at?: string
          completed_by?: string | null
          completed_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'stock_counts_category_id_fkey'
            columns: ['category_id']
            isOneToOne: false
            referencedRelation: 'categories'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'stock_counts_completed_by_fkey'
            columns: ['completed_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'stock_counts_started_by_fkey'
            columns: ['started_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      store_settings: {
        Row: {
          id: number
          store_name: string
          tagline: string | null
          phone: string | null
          whatsapp: string | null
          email: string | null
          pickup_enabled: boolean
          pickup_address: string | null
          pickup_hours: string | null
          mpesa_enabled: boolean
          card_enabled: boolean
          cod_enabled: boolean
          free_delivery_threshold: number | null
          low_stock_default: number
          return_window_days: number
          announcement: string | null
          instagram_url: string | null
          facebook_url: string | null
          tiktok_url: string | null
          receipt_footer: string | null
          updated_at: string
        }
        Insert: {
          id?: number
          store_name?: string
          tagline?: string | null
          phone?: string | null
          whatsapp?: string | null
          email?: string | null
          pickup_enabled?: boolean
          pickup_address?: string | null
          pickup_hours?: string | null
          mpesa_enabled?: boolean
          card_enabled?: boolean
          cod_enabled?: boolean
          free_delivery_threshold?: number | null
          low_stock_default?: number
          return_window_days?: number
          announcement?: string | null
          instagram_url?: string | null
          facebook_url?: string | null
          tiktok_url?: string | null
          receipt_footer?: string | null
          updated_at?: string
        }
        Update: {
          id?: number
          store_name?: string
          tagline?: string | null
          phone?: string | null
          whatsapp?: string | null
          email?: string | null
          pickup_enabled?: boolean
          pickup_address?: string | null
          pickup_hours?: string | null
          mpesa_enabled?: boolean
          card_enabled?: boolean
          cod_enabled?: boolean
          free_delivery_threshold?: number | null
          low_stock_default?: number
          return_window_days?: number
          announcement?: string | null
          instagram_url?: string | null
          facebook_url?: string | null
          tiktok_url?: string | null
          receipt_footer?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      variant_costs: {
        Row: {
          variant_id: string
          cost_price: number
          updated_by: string | null
          updated_at: string
        }
        Insert: {
          variant_id: string
          cost_price?: number
          updated_by?: string | null
          updated_at?: string
        }
        Update: {
          variant_id?: string
          cost_price?: number
          updated_by?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'variant_costs_updated_by_fkey'
            columns: ['updated_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'variant_costs_variant_id_fkey'
            columns: ['variant_id']
            isOneToOne: true
            referencedRelation: 'product_variants'
            referencedColumns: ['id']
          }
        ]
      }
      wishlist_items: {
        Row: {
          user_id: string
          product_id: string
          created_at: string
        }
        Insert: {
          user_id: string
          product_id: string
          created_at?: string
        }
        Update: {
          user_id?: string
          product_id?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'wishlist_items_product_id_fkey'
            columns: ['product_id']
            isOneToOne: false
            referencedRelation: 'products'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'wishlist_items_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
    }
    Views: {
      
    }
    Functions: {
      adjust_stock: {
        Args: {
          p_variant: string
          p_delta: number
          p_reason: Database['public']['Enums']['stock_reason']
          p_note: string
        }
        Returns: number
      }
      apply_order_discount: {
        Args: {
          p_order: string
          p_amount: number
          p_reason: string
        }
        Returns: undefined
      }
      can_manage_category: {
        Args: {
          p_category: string
        }
        Returns: boolean
      }
      can_manage_product: {
        Args: {
          p_product: string
        }
        Returns: boolean
      }
      can_view_margins: {
        Args: Record<string, never>
        Returns: boolean
      }
      cancel_my_order: {
        Args: {
          p_order: string
        }
        Returns: undefined
      }
      cancel_stock_count: {
        Args: {
          p_count: string
        }
        Returns: undefined
      }
      close_cash_session: {
        Args: {
          p_session: string
          p_counted: number
          p_notes: string
        }
        Returns: Json
      }
      complete_stock_count: {
        Args: {
          p_count: string
          p_zero_uncounted?: boolean
        }
        Returns: number
      }
      coupon_discount: {
        Args: {
          p_code: string
          p_subtotal: number
        }
        Returns: number
      }
      dashboard_counts: {
        Args: Record<string, never>
        Returns: Json
      }
      expire_unpaid_orders: {
        Args: {
          p_minutes?: number
        }
        Returns: number
      }
      fail_payment: {
        Args: {
          p_payment: string
          p_raw: Json
        }
        Returns: undefined
      }
      hit_rate_limit: {
        Args: {
          p_key: string
          p_limit: number
          p_window_seconds: number
        }
        Returns: boolean
      }
      is_manager: {
        Args: Record<string, never>
        Returns: boolean
      }
      is_owner: {
        Args: Record<string, never>
        Returns: boolean
      }
      is_privileged: {
        Args: Record<string, never>
        Returns: boolean
      }
      is_staff: {
        Args: Record<string, never>
        Returns: boolean
      }
      mark_order_paid: {
        Args: {
          p_order: string
          p_method: Database['public']['Enums']['payment_method']
          p_reference: string
        }
        Returns: undefined
      }
      my_role: {
        Args: Record<string, never>
        Returns: Database['public']['Enums']['app_role']
      }
      next_barcode: {
        Args: Record<string, never>
        Returns: string
      }
      open_cash_session: {
        Args: {
          p_float: number
        }
        Returns: string
      }
      place_order: {
        Args: {
          p_customer: string
          p_items: Json
          p_contact_name: string
          p_contact_phone: string
          p_contact_email: string
          p_delivery_method: Database['public']['Enums']['delivery_method']
          p_zone: string
          p_address: string
          p_notes: string
          p_payment: Database['public']['Enums']['payment_method']
          p_coupon: string
        }
        Returns: Json
      }
      receive_stock: {
        Args: {
          p_variant: string
          p_quantity: number
          p_new_cost?: number
          p_note?: string
        }
        Returns: number
      }
      record_in_store_sale: {
        Args: {
          p_items: Json
          p_payment: Database['public']['Enums']['payment_method']
          p_discount?: number
          p_discount_reason?: string
          p_reference?: string
          p_amount_tendered?: number
          p_customer_name?: string
          p_customer_phone?: string
          p_await_stk?: boolean
        }
        Returns: Json
      }
      record_stock_count: {
        Args: {
          p_count: string
          p_variant: string
          p_quantity: number
          p_increment?: boolean
        }
        Returns: number
      }
      refresh_product_rollup: {
        Args: {
          p_product: string
        }
        Returns: undefined
      }
      refund_order: {
        Args: {
          p_order: string
          p_reason: string
        }
        Returns: undefined
      }
      report_profit: {
        Args: {
          p_from: string
          p_to: string
          p_group?: string
          p_category?: string
        }
        Returns: {
          key: string | null
          label: string | null
          category: string | null
          units: number | null
          sales: number | null
          cost: number | null
          profit: number | null
          margin_pct: number | null
        }[]
      }
      report_sales_by_day: {
        Args: {
          p_from: string
          p_to: string
        }
        Returns: {
          day: string | null
          sales: number | null
          orders: number | null
          profit: number | null
        }[]
      }
      report_sales_summary: {
        Args: {
          p_from: string
          p_to: string
        }
        Returns: Json
      }
      report_staff_performance: {
        Args: {
          p_from: string
          p_to: string
        }
        Returns: {
          user_id: string | null
          full_name: string | null
          role: Database['public']['Enums']['app_role'] | null
          is_active: boolean | null
          orders: number | null
          sales: number | null
          avg_order: number | null
          items: number | null
          voided_sales: number | null
          voids_performed: number | null
          discounts: number | null
          last_sale: string | null
        }[]
      }
      report_stock_valuation: {
        Args: Record<string, never>
        Returns: {
          category_id: string | null
          category: string | null
          variants: number | null
          units: number | null
          cost_value: number | null
          retail_value: number | null
        }[]
      }
      report_top_products: {
        Args: {
          p_from: string
          p_to: string
          p_limit?: number
        }
        Returns: {
          product_id: string | null
          name: string | null
          image_url: string | null
          units: number | null
          sales: number | null
        }[]
      }
      settle_payment: {
        Args: {
          p_payment: string
          p_receipt: string
          p_raw: Json
        }
        Returns: Json
      }
      start_stock_count: {
        Args: {
          p_title: string
          p_category?: string
        }
        Returns: string
      }
      update_order_status: {
        Args: {
          p_order: string
          p_status: Database['public']['Enums']['order_status']
          p_note?: string
        }
        Returns: undefined
      }
    }
    Enums: {
      app_role: 'owner' | 'sales_manager' | 'sales_attendant' | 'customer'
      attribute_kind: 'size' | 'colour'
      coupon_type: 'percent' | 'fixed'
      delivery_method: 'courier' | 'pickup' | 'in_store'
      notification_type: 'new_order' | 'payment_received' | 'low_stock' | 'order_needs_action' | 'new_review' | 'cash_discrepancy' | 'order_update' | 'system'
      order_channel: 'online' | 'in_store'
      order_status: 'placed' | 'confirmed' | 'packed' | 'out_for_delivery' | 'ready_for_pickup' | 'delivered' | 'collected' | 'returned' | 'cancelled'
      payment_method: 'mpesa' | 'card' | 'cod' | 'cash'
      payment_status: 'unpaid' | 'pending' | 'paid' | 'failed' | 'refunded'
      review_status: 'pending' | 'approved' | 'rejected'
      stock_reason: 'initial' | 'restock' | 'sale' | 'return' | 'void' | 'damage' | 'loss' | 'correction' | 'stock_take'
    }
    CompositeTypes: Record<string, never>
  }
}

type PublicSchema = Database['public']
export type Tables<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Row']
export type TablesInsert<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Insert']
export type TablesUpdate<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Update']
export type Views<T extends keyof PublicSchema['Views']> = PublicSchema['Views'][T]['Row']
export type Enums<T extends keyof PublicSchema['Enums']> = PublicSchema['Enums'][T]
